# Generated by Django 4.1.6 on 2023-03-08 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('des', models.CharField(max_length=255)),
                ('img1', models.ImageField(upload_to='', verbose_name='/media')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='/media')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='', verbose_name='/media')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='', verbose_name='/media')),
            ],
        ),
        migrations.CreateModel(
            name='desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number_seats', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Emoloye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('addres', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='loader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=100, null=True)),
                ('name2', models.CharField(blank=True, max_length=100, null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='', verbose_name='/media')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='', verbose_name='/media')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='', verbose_name='/media')),
                ('offPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('descpription', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reserveDesk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.IntegerField(choices=[(13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (22, '23:00')])),
                ('desk', models.IntegerField(choices=[(2, 'دو'), (3, 'سه'), (4, 'چهار '), (5, 'پنج '), (6, 'شش'), (7, 'هفت'), (8, 'هشت'), (9, 'نه'), (10, 'ده'), (11, 'یازده'), (12, 'دوازده'), (13, 'سیزده'), (14, 'چهارده'), (15, 'پانزده'), (16, 'شانزده'), (17, 'هوده'), (18, 'هجده'), (19, 'نوزده'), (20, 'بیست'), (30, 'سی'), (40, 'چهل')])),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('des', models.CharField(max_length=100)),
                ('img1', models.ImageField(upload_to='', verbose_name='/media')),
            ],
        ),
        migrations.CreateModel(
            name='registerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('phone', models.CharField(max_length=50)),
                ('addres', models.CharField(max_length=200)),
                ('paymentToAddres', models.BooleanField()),
                ('total_price', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturan.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='ProductID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturan.product'),
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturan.registermodel'),
        ),
        migrations.CreateModel(
            name='buy_Finish_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Reference_num', models.CharField(blank=True, max_length=150, null=True)),
                ('TotalPrice', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resturan.order')),
            ],
        ),
    ]
